In [2]:
import pandas as pd
import requests
import logging
import json
from alpha_vantage.timeseries import TimeSeries
from datetime import date, timedelta

In [3]:
logging.basicConfig(format='%(asctime)s : %(lineno)d : %(levelname)s : %(message)s', level=logging.DEBUG)

In [4]:
covid_response = requests.get("https://covidtracking.com/api/states/daily").json()
covid_dataframe = pd.DataFrame(covid_response)
covid_dataframe

2020-05-08 17:45:56,913 : 959 : DEBUG : Starting new HTTPS connection (1): covidtracking.com:443
2020-05-08 17:45:56,999 : 437 : DEBUG : https://covidtracking.com:443 "GET /api/states/daily HTTP/1.1" 200 298423

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200508,AK,377.0,25096.0,NaN,16.0,NaN,NaN,NaN,NaN,...,NaN,25473,25473,25473,02,0.0,0.0,1129.0,3.0,1132.0
1,20200508,AL,9221.0,110893.0,NaN,NaN,1207.0,NaN,454.0,NaN,...,1207.0,120114,120114,120114,01,26.0,29.0,4618.0,323.0,4941.0
2,20200508,AR,3694.0,60300.0,NaN,70.0,466.0,NaN,NaN,14.0,...,466.0,63994,63994,63994,05,1.0,4.0,3916.0,83.0,3999.0
3,20200508,AS,0.0,83.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,83,83,83,60,0.0,0.0,0.0,0.0,0.0
4,20200508,AZ,10526.0,109381.0,NaN,730.0,1482.0,295.0,NaN,197.0,...,1482.0,119907,119907,119907,04,67.0,33.0,8240.0,581.0,8821.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3596,20200126,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
3597,20200125,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
3598,20200124,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
3599,20200123,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
3600,20200122,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,NaN,NaN,NaN,NaN,NaN

In [79]:
#alphavantage api

# Your key here
key = 'R2GMX96108X4BTMR'
ts = TimeSeries(key)
aapl, meta = ts.get_daily(symbol='AAPL')
# print(json.dumps(aapl, indent=4))
print(aapl['2020-01-02'])

2020-05-08 21:15:28,053 : 959 : DEBUG : Starting new HTTPS connection (1): www.alphavantage.co:443
2020-05-08 21:15:28,191 : 437 : DEBUG : https://www.alphavantage.co:443 "GET /query?function=TIME_SERIES_DAILY&symbol=AAPL&outputsize=compact&apikey=R2GMX96108X4BTMR&datatype=json HTTP/1.1" 200 None

{'1. open': '296.2400', '2. high': '300.6000', '3. low': '295.1900', '4. close': '300.3500', '5. volume': '33911864'}

In [77]:
# #US Bureau of Labor Statistics\
areaCodesDF = pd.read_csv("bureauoflaborstats.csv")
fips_dict = pd.read_csv("fipscodes.csv")
fips_dict = fips_dict[["State Abbreviation","FIPS Code"]]
fips_dict = fips_dict.to_dict()

#If we want to get more granular, we can switch the area_type_code from A to N
areaCodesList = areaCodesDF[areaCodesDF["area_type_code"]=="A"]
areaCodesList = list(areaCodesList["area_code"].values)

master_unemp_DF = pd.DataFrame({"year":[],"periodName":[],"value":[],"state":[]})

for x in areaCodesList:
    try:
        seriesid = f"LAU{x}03"
        fips_code = x[2:4]
        headers = {'Content-type': 'application/json'} 
        data = json.dumps({"seriesid": [seriesid],"startyear":"2010", "endyear":"2020","registrationkey":"99dc14b091ad411393d936e7b627945f"})
        response = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers).json()
        state_unemp_DF = pd.DataFrame(response['Results']['series'][0]['data'])
        state_unemp_DF['state'] = fips_dict['State Abbreviation'][int(fips_code)]
        state_unemp_DF = state_unemp_DF[["year","periodName","value","state"]]
        state_unemp_DF['value'] = state_unemp_DF['value'].astype('float')
        master_unemp_DF = master_unemp_DF.append(state_unemp_DF)
    except:
        logging.error(f"Error retrieving data")

master_unemp_DF = pd.pivot_table(master_unemp_DF, index=['state','periodName'], columns=['year'], values=['value'])
master_unemp_DF

2020-05-08 20:35:33,091 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:33,317 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1387
2020-05-08 20:35:33,324 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:33,511 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1373
2020-05-08 20:35:33,518 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:33,733 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1338
2020-05-08 20:35:33,739 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:33,941 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1365
2020-05-08 20:35:33,947 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:34,151 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1358
2020-05-08 20:35:34,159 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:34,374 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1367
2020-05-08 20:35:34,381 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:34,581 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1361
2020-05-08 20:35:34,587 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:34,773 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1374
2020-05-08 20:35:34,780 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:34,968 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1366
2020-05-08 20:35:34,974 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:35,188 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1371
2020-05-08 20:35:35,195 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:35,398 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1372
2020-05-08 20:35:35,404 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:35,594 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1362
2020-05-08 20:35:35,600 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:35,798 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1342
2020-05-08 20:35:35,804 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:35,999 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1349
2020-05-08 20:35:36,007 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:36,210 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1362
2020-05-08 20:35:36,217 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:36,410 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1333
2020-05-08 20:35:36,416 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:36,613 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1339
2020-05-08 20:35:36,619 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:36,836 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1348
2020-05-08 20:35:36,843 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:37,065 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1361
2020-05-08 20:35:37,071 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:37,268 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1361
2020-05-08 20:35:37,275 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:37,489 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1356
2020-05-08 20:35:37,496 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:37,742 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1385
2020-05-08 20:35:37,748 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:37,970 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1366
2020-05-08 20:35:37,976 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:38,160 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1362
2020-05-08 20:35:38,166 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:38,401 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1376
2020-05-08 20:35:38,407 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:38,606 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1383
2020-05-08 20:35:38,612 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:38,866 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1354
2020-05-08 20:35:38,872 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:39,098 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1333
2020-05-08 20:35:39,104 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:39,311 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1376
2020-05-08 20:35:39,318 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:39,536 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1319
2020-05-08 20:35:39,543 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:39,756 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1362
2020-05-08 20:35:39,765 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:39,971 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1344
2020-05-08 20:35:39,977 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:40,188 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1328
2020-05-08 20:35:40,195 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:40,382 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1368
2020-05-08 20:35:40,389 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:40,635 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1342
2020-05-08 20:35:40,642 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:40,840 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1377
2020-05-08 20:35:40,847 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:41,086 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1342
2020-05-08 20:35:41,092 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:41,285 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1369
2020-05-08 20:35:41,292 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:41,552 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1357
2020-05-08 20:35:41,558 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:41,769 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1369
2020-05-08 20:35:41,775 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:42,000 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1398
2020-05-08 20:35:42,007 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:42,200 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1342
2020-05-08 20:35:42,207 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:42,402 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1331
2020-05-08 20:35:42,409 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:42,661 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1339
2020-05-08 20:35:42,666 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:42,877 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1341
2020-05-08 20:35:42,884 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:43,161 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1351
2020-05-08 20:35:43,167 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:43,409 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1371
2020-05-08 20:35:43,417 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:43,661 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1361
2020-05-08 20:35:43,667 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:43,850 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1380
2020-05-08 20:35:43,856 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:44,098 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1371
2020-05-08 20:35:44,100 : 27 : ERROR : Error retrieving data
2020-05-08 20:35:44,102 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:44,318 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1343
2020-05-08 20:35:44,321 : 27 : ERROR : Error retrieving data
2020-05-08 20:35:44,323 : 959 : DEBUG : Starting new HTTPS connection (1): api.bls.gov:443
2020-05-08 20:35:44,553 : 437 : DEBUG : https://api.bls.gov:443 "POST /publicAPI/v2/timeseries/data/ HTTP/1.1" 200 1448
2020-05-08 20:35:44,556 : 27 : ERROR : Error retrieving data

                 value
year              2010  2011 2012 2013 2014 2015 2016 2017 2018 2019 2020
state periodName
AL    April       10.4   9.4  7.2  6.3  6.2  5.6  5.3  4.1  3.5  2.6  NaN
      August      10.1  10.0  8.5  7.5  7.0  6.4  6.0  4.3  4.0  3.0  NaN
      December     9.8   7.9  7.2  6.8  5.8  5.8  5.4  3.7  3.5  2.5  NaN
      February    12.1  10.5  8.4  7.9  7.8  6.3  6.2  5.6  4.4  3.8  2.9
      January     12.3  11.0  8.3  8.2  7.6  6.4  6.3  6.0  4.3  4.2  3.2
...                ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
WY    March        9.3   8.9  7.8  7.4  7.5  7.6  6.9  5.6  6.0  5.2  6.1
      May          8.3   7.8  7.3  6.3  6.3  6.8  6.0  4.7  5.0  4.5  NaN
      November     8.3   7.1  7.0  6.3  6.0  5.9  5.1  4.9  4.5  4.8  NaN
      October      8.0   7.2  7.0  6.2  5.8  5.7  5.3  4.6  4.5  4.6  NaN
      September    8.1   7.5  7.0  6.0  5.9  5.9  5.4  4.6  4.5  4.3  NaN

[588 rows x 11 columns]